---
  team_mappings:
    Customer Service: 0
    Community: 5
    Outreach: 15
    Marketing: 20
    Communications: 25
    Operations: 30
    Product: 40
    Design: 60
    Engineering: 90
    Data: 100
  specialty_mappings:
    Backend: 0
    Data: 20
    Frontend: 30
    Mobile: 50
    Finance: 100
    Legal: 120
  weights:
    table: 0.6
    days_here: 0.2
    team: 0.9
    specialty: 0.1
  min_lunch_group_size: 5
