---
  team_mappings:
    Customer Service: 0
    Communications: 5
    Outreach: 15
    Operations: 30
    Product Manager: 40
    Design: 60
    Engineering: 90
    Executive: 150
  specialty_mappings:
    Backend: -20
    Data: -10
    Frontend: -15
    Mobile: 5
    Finance: 0
    Legal: 40
  weights:
    floor: 0.1
    days_here: 0.2
    team: 0.9
    specialty: 0.1
  min_lunch_group_size: 4
