---
  team_mappings:
    Community Support: 100
    Community: 90
    Marketing: 80
    Communications: 70
    Operations: 50
    Product: 40
    Design: 30
    Engineering: 20
    Data: 0
  specialty_mappings:
    Backend: 0
    Data: 20
    Frontend: 30
    Mobile: 50
    Finance: 100
    Legal: 120
  weights:
    table: 0.4
    days_here: 0.2
    team: 0.9
    specialty: 0.1
  min_lunch_group_size: 5
